<a href="https://colab.research.google.com/github/AbhishekSatpathy4848/SpeechEmotionRecognition/blob/main/SpeechEmotionRecognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas
import numpy
import librosa
import librosa.display
import librosa.feature
import matplotlib.pyplot as plt
import IPython.display as ipd
import seaborn
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import ReduceLROnPlateau,EarlyStopping
numpy.set_printoptions(suppress=True,formatter={'float_kind':'{:f}'.format})
from sklearn.model_selection import train_test_split

In [ ]:
paths=[]
label=[]

In [ ]:
dnew={}
x="./drive/MyDrive/TESS Toronto emotional speech set data"
for i in os.listdir(x):
  emotion=i[4:].lower()
  path=x+"/"+i
  s=os.listdir(path)
  for j in s:
    complete_audio_file_path=path+"/"+j
    paths.append(complete_audio_file_path)
    label.append(emotion)

In [ ]:
x="./drive/MyDrive/ALL"
for i in os.listdir(x):
  p=x+"/"+i
  paths.append(p)
  if "_su" in i:
    label.append("pleasant_surprise")
  elif "_a" in i:
    label.append("angry")
  elif "_d" in i:
    label.append("disgust")
  elif "_sa" in i:
    label.append("sad")
  elif "_n" in i:
    label.append("neutral")
  elif "_h" in i:
    label.append("happy")
  elif "_f" in i:
    label.append("fear")

In [ ]:
x="./drive/MyDrive/AudioWAV"
for i in os.listdir(x):
  p=x+"/"+i
  paths.append(p)
  if "_ANG" in i:
    label.append("angry")
  elif "_DIS" in i:
    label.append("disgust")
  elif "_SAD" in i:
    label.append("sad")
  elif "_NEU" in i:
    label.append("neutral")
  elif "_HAP" in i:
    label.append("happy")
  elif "_FEA" in i:
    label.append("fear")
dnew={"Emotion":label,"Path":paths}

In [ ]:
x="./drive/MyDrive/archive"
for i in os.listdir(x):
  h=x+"/"+i
  y=os.listdir(h)
  for j in y:
    p=h+"/"+j
    paths.append(p)
    if j[6:8]=="01":
      label.append("neutral")
    elif j[6:8]=="02":
      label.append("calm")
    elif j[6:8]=="03":
      label.append("happy")
    elif j[6:8]=="04":
      label.append("sad")
    elif j[6:8]=="05":
      label.append("angry")
    elif j[6:8]=="06":
       label.append("fear")
    elif j[6:8]=="07":
      label.append("disgust")
    elif j[6:8]=="08":
      label.append("pleasant_surprise")
dnew={"Emotion":label,"Path":paths}

NotADirectoryError: ignored

In [ ]:
Audio_DataFrame=pandas.DataFrame(dnew)
Audio_DataFrame

In [ ]:
Audio_DataFrame.to_csv("./drive/MyDrive/IEEE")

In [ ]:
print(Audio_DataFrame.groupby(["Emotion"])["Emotion"].count())
Count_Emotion=numpy.array(Audio_DataFrame.groupby(["Emotion"])["Emotion"].count())
print(Count_Emotion)

In [ ]:
Unique_Emo=numpy.sort(Audio_DataFrame.Emotion.unique())

In [ ]:
Bar_Plot_Dictionary={"Emotion":Unique_Emo,"Count":Count_Emotion}

In [ ]:
Bar_Plot_DataFrame=pandas.DataFrame(Bar_Plot_Dictionary)

In [ ]:
plt.figure(figsize=(15,10))
seaborn.barplot(x="Emotion",y="Count",data=Bar_Plot_DataFrame)

In [ ]:
def Display_Amplitude_Time_Waveplot(audio_path):
  l,sr=librosa.load(audio_path)
  plt.figure(figsize=(25,20))
  librosa.display.waveplot(l,alpha=0.8)
  plt.show()

In [ ]:
def Frequency_Spectrum(audio_path):
  l,sr=librosa.load(audio_path)
  Fast_Fourier_Transform=numpy.fft.fft(l)
  Fast_Fourier_Transform=numpy.abs(Fast_Fourier_Transform)
  frequency=numpy.linspace(0,sr,len(Fast_Fourier_Transform))
  num_frequency_bins=int(len(frequency)/2)
  plt.figure(figsize=(15,10))
  plt.plot(frequency[:num_frequency_bins],Fast_Fourier_Transform[:num_frequency_bins])
  plt.show()


In [ ]:
def Mel_Spectrogram(audio_path,frame_length,hop_length,mel_bands):
  l,sr=librosa.load(audio_path)
  mel_spectrogram=librosa.feature.melspectrogram(l,sr=sr,n_fft=frame_length,hop_length=hop_length,n_mels=mel_bands)
  mel_to_log=librosa.power_to_db(mel_spectrogram)
  plt.figure(figsize=(15,10))
  librosa.display.specshow(mel_to_log,sr=sr,hop_length=hop_length,x_axis="time",y_axis="mel")
  plt.colorbar(format="%+2.f")
  plt.show()

In [ ]:
FRAME_SIZE=2048
HOP_SIZE=512

In [ ]:
print("Fear")
P=Audio_DataFrame["Path"][0]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
print("Sad")
P=Audio_DataFrame["Path"][1]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
print("Pleasant Surprise")
P=Audio_DataFrame["Path"][943]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
print("Happy")
P=Audio_DataFrame["Path"][670]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
print("Disgust")
P=Audio_DataFrame["Path"][1321]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
print("Neutral")
P=Audio_DataFrame["Path"][1527]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
print("Angry")
P=Audio_DataFrame["Path"][3162]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
print("Calm")
P=Audio_DataFrame["Path"][11601]
Display_Amplitude_Time_Waveplot(P)
Frequency_Spectrum(P)
Mel_Spectrogram(P,FRAME_SIZE,HOP_SIZE,100)
ipd.Audio(P)

In [ ]:
def extract_features(signal):
  zero_crossing_rate=librosa.feature.zero_crossing_rate(signal)[0]
  rms=librosa.feature.rms(signal)[0]
  mfccs=librosa.feature.mfcc(signal)
  chr_stft=librosa.feature.chroma_stft(signal)
  mel_spectrogram=librosa.feature.melspectrogram(signal)
  mel_spec=librosa.power_to_db(mel_spectrogram)
  return numpy.hstack((numpy.mean(zero_crossing_rate.T,axis=0),numpy.mean(chr_stft.T,axis=0),numpy.mean(mfccs.T,axis=0),numpy.mean(rms.T,axis=0),numpy.mean(mel_spec.T,axis=0)))

In [ ]:
def get_features(path):
  audio,sr=librosa.load(path,duration=2.5,offset=0.6)

  features_original=extract_features(audio) # original audio

  noise=numpy.random.normal(0,audio.std(),audio.size)
  augmented_noise=audio+noise*0.4
  features_noise=extract_features(augmented_noise) # with white noise

  augmented_time_stretch=librosa.effects.time_stretch(audio,0.8)
  augmented_pitch_shift_on_time_stretch=librosa.effects.pitch_shift(augmented_time_stretch,sr,0.7) #pitch shift on time stretch audio
  features_pitch_shift_on_time_stretch=extract_features(augmented_pitch_shift_on_time_stretch)

  return numpy.vstack((features_original,features_noise,features_pitch_shift_on_time_stretch))

In [ ]:
P=Audio_DataFrame["Path"][1005]
print(get_features(P).shape)

NameError: ignored

In [ ]:
P=Audio_DataFrame["Path"][101]
audio,sr=librosa.load(P,duration=1)
print(len(audio))
librosa.get_duration(y=audio, sr=sr)

In [ ]:
X=[]
Y=[]

In [ ]:
iterations=int(len(Audio_DataFrame)/3)
for i in range(0,iterations):
  audio_file_features=get_features(Audio_DataFrame["Path"][i])
  for j in audio_file_features:
    X.append(j)
    Y.append(Audio_DataFrame["Emotion"][i])


In [ ]:
for i in range(iterations,2*iterations):
  audio_file_features=get_features(Audio_DataFrame["Path"][i])
  for j in audio_file_features:
    X.append(j)
    Y.append(Audio_DataFrame["Emotion"][i])


In [ ]:
for i in range(2*iterations,3*iterations):
  audio_file_features=get_features(Audio_DataFrame["Path"][i])
  for j in audio_file_features:
    X.append(j)
    Y.append(Audio_DataFrame["Emotion"][i])


NameError: ignored

In [ ]:
Final_Emotion_Dict={"Features":X,"Label":Y}
Final_DataFrame=pandas.DataFrame(Final_Emotion_Dict)

In [ ]:
Final_DataFrame.to_csv("./drive/MyDrive/Final_Emotion_DataFrame")

In [ ]:
Final_DataFrame.to_csv("./drive/MyDrive/Final_Emotion_DataFrame2")

In [ ]:
Final_DataFrame.head

In [ ]:
pandas.get_dummies(Final_DataFrame)

NameError: ignored

In [ ]:
one_hot_encoded=pandas.get_dummies(Final_DataFrame["Label"])

In [ ]:
one_hot_encoded

In [ ]:
one_hot_encoded.to_csv("./drive/MyDrive/One_Hot_Encoded")

In [ ]:
Final_Data_Sample.shape

NameError: ignored

In [ ]:
df=pandas.read_csv("/content/drive/MyDrive/Final_Emotion_DataFrame")
x=[]
for s in Final_DataFrame["Features"]:
  l=eval(s.replace(" ",","))
  x.append(l)
  i+=1
x=numpy.array(x)
print(x.shape)
print(x.size)
x_test,x_train=train_test_split(x,)
print(x_test.shape,x_train.shape)

In [ ]:
One_Hot_Encoding=pandas.read_csv("/content/drive/MyDrive/One_Hot_Encoded")
One_Hot_Encoded=numpy.array(One_Hot_Encoding)
One_Hot_Encoded=One_Hot_Encoded[:,1:]
one_hot_encoded=numpy.array(One_Hot_Encoded)
Final_DataFrame=pandas.read_csv("/content/drive/MyDrive/Final_Emotion_DataFrame")
i=0
Test_Data=[]
for s in Final_DataFrame["Features"]:
  l=eval(s.replace(" ",","))
  Test_Data.append(l)
  i+=1
Final_Data_Sample=numpy.array(Test_Data)
Final_Data_Sample.resize((36486,18,9))
print(Final_Data_Sample.shape)
print(one_hot_encoded.shape)
Train_Set_Data,Test_Set_Data,Train_Set_Label,Test_Set_Label=train_test_split(Final_Data_Sample,one_hot_encoded)
print(Train_Set_Data.shape)
print(Test_Set_Data.shape)
print(Train_Set_Label.shape)
print(Test_Set_Label.shape)

(36486, 18, 9)
(36486, 8)
(27364, 18, 9)
(9122, 18, 9)
(27364, 8)
(9122, 8)


In [ ]:
# print(one_hot_encoded)
# print(Final_Data_Sample)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[[0.042959 0.261424 0.296838 ... 0.280429 0.232333 0.171661]
  [0.244194 0.258932 0.281713 ... -2.338926 -17.323891 4.168365]
  [5.022225 -12.721068 1.278307 ... -7.408150 -5.481190 -1.888926]
  ...
  [-49.355976 -47.559132 -48.035919 ... -49.856705 -48.523529 -48.596825]
  [-46.361935 -46.811409 -46.493896 ... -47.821812 -49.271778 -49.273075]
  [-49.429184 -49.450012 -49.872711 ... -52.810745 -55.504650 -60.245804]]

 [[0.282416 0.402338 0.454617 ... 0.361177 0.293570 0.262196]
  [0.365608 0.383405 0.400234 ... 1.297497 -7.292877 -4.258008]
  [-0.861019 -2.346322 -2.018469 ... -5.436645 -5.464641 -2.311298]
  ...
  [-18.575430 -18.093674 -18.741252 ... -18.949659 -18.582718 -18.348257]
  [-18.375681 -18.559184 -18.538596 ... -18.977818 -18.969135 -18.732208]
  [-18.423869 -18.624900 -19.027211 ... -18.808506 -18.689530 -18.723160]]

 [[0.047099 0.261881 0.180833 ..

In [ ]:
# model=Sequential()
# model.add(layers.Conv2D(256,padding='same',kernel_size=5,activation="relu"))
# model.add(layers.MaxPooling2D(pool_size=3,strides=2,padding="same"))
# model.add(layers.Conv2D(128,padding='same',kernel_size=5,activation="relu"))
# model.add(layers.MaxPooling2D(pool_size=3,strides=2,padding="same"))
# model.add(layers.Conv2D(128,padding='same',kernel_size=5,activation="relu"))
# model.add(layers.MaxPooling2D(pool_size=3,strides=2,padding="same"))
# model.add(layers.Conv2D(128,padding='same',kernel_size=3,activation="relu"))
# model.add(layers.MaxPooling2D(pool_size=3,strides=2,padding="same"))
# model.add(layers.Dropout(rate=0.3))
# model.add(layers.Flatten())
# model.add(layers.Dense(8, activation="softmax"))
# model.compile(Adam(learning_rate=0.0001),loss="categorical_crossentropy",metrics=["accuracy"])
# rlrp = ReduceLROnPlateau(monitor='loss', factor=0.4, verbose=0, patience=1, min_lr=0.0000001)
# history=model.fit(Train_Set_Data, Train_Set_Label, batch_size=32, epochs=100, validation_data=(Test_Set_Data, Test_Set_Label), callbacks=[rlrp])
# # model.fit(Train_Set_Data,Train_Set_Label,validation_split=0.2,batch_size=32,epochs=50,verbose=1,shuffle=True,callbacks=[rlrp])
# # print(history)
# # print(history.history.keys())

Epoch 1/100


ValueError: ignored

In [ ]:
model=Sequential()
model.add(layers.Conv1D(256,padding='same',kernel_size=5,activation="relu"))
model.add(layers.MaxPooling1D(pool_size=3,strides=2,padding="same"))
model.add(layers.Conv1D(128,padding='same',kernel_size=5,activation="relu"))
model.add(layers.MaxPooling1D(pool_size=3,strides=2,padding="same"))
model.add(layers.Conv1D(128,padding='same',kernel_size=5,activation="relu"))
model.add(layers.MaxPooling1D(pool_size=3,strides=2,padding="same"))
model.add(layers.Conv1D(64,padding='same',kernel_size=5,activation="relu"))
model.add(layers.MaxPooling1D(pool_size=3,strides=2,padding="same"))
model.add(layers.Dropout(rate=0.2))
model.add(layers.Flatten())
model.add(layers.Dense(8, activation="softmax"))
model.compile(Adam(learning_rate=0.00015),loss="categorical_crossentropy",metrics=["accuracy"])
rlrp = ReduceLROnPlateau(monitor='loss', factor=0.4, verbose=0, patience=1, min_lr=0.0000000000001)
es=EarlyStopping(monitor='loss')
history=model.fit(Train_Set_Data, Train_Set_Label, batch_size=32, epochs=100, validation_data=(Test_Set_Data, Test_Set_Label), callbacks=[rlrp],shuffle=True)
# model.fit(Train_Set_Data,Train_Set_Label,validation_split=0.2,batch_size=32,epochs=50,verbose=1,shuffle=True,callbacks=[rlrp])
# print(history)
# print(history.history.keys())

Epoch 1/100
856/856 [==============================] - 5s 5ms/step - loss: 1.7890 - accuracy: 0.3104 - val_loss: 1.5443 - val_accuracy: 0.4037 - lr: 1.5000e-04
Epoch 2/100
856/856 [==============================] - 4s 5ms/step - loss: 1.5225 - accuracy: 0.3936 - val_loss: 1.4426 - val_accuracy: 0.4253 - lr: 1.5000e-04
Epoch 3/100
856/856 [==============================] - 5s 6ms/step - loss: 1.3953 - accuracy: 0.4409 - val_loss: 1.3221 - val_accuracy: 0.4821 - lr: 1.5000e-04
Epoch 4/100
856/856 [==============================] - 5s 6ms/step - loss: 1.3197 - accuracy: 0.4679 - val_loss: 1.3249 - val_accuracy: 0.4743 - lr: 1.5000e-04
Epoch 5/100
856/856 [==============================] - 5s 6ms/step - loss: 1.2820 - accuracy: 0.4867 - val_loss: 1.2308 - val_accuracy: 0.5067 - lr: 1.5000e-04
Epoch 6/100
856/856 [==============================] - 4s 5ms/step - loss: 1.2473 - accuracy: 0.4996 - val_loss: 1.2304 - val_accuracy: 0.5077 - lr: 1.5000e-04
Epoch 7/100
856/856 [===================

In [ ]:
model.save("./drive/MyDrive/ModelSpeechEmotionRecognition")

In [ ]:
Emotion_indices={0:"Angry",1:"Calm",2:"Disgust",3:"Fear",4:"Happy",5:"Neutral",6:"Pleasant Surprise",7:"Sad"}

In [ ]:
i=0
for j in model.predict(Test_Set_Data,batch_size=10):
  highest_probability=list(j).index(max(list(j)))
  correct_label=list(One_Hot_Encoded[i]).index(max(list(One_Hot_Encoded[i])))
  # print(One_Hot_Encoded[i])
  print(Emotion_indices[highest_probability],Emotion_indices[correct_label])
  i+=1

Streaming output truncated to the last 5000 lines.
[1 0 0 0 0 0 0 0]
Happy Angry
[1 0 0 0 0 0 0 0]
Disgust Angry
[1 0 0 0 0 0 0 0]
Angry Angry
[1 0 0 0 0 0 0 0]
Sad Angry
[1 0 0 0 0 0 0 0]
Pleasant Surprise Angry
[1 0 0 0 0 0 0 0]
Neutral Angry
[1 0 0 0 0 0 0 0]
Sad Angry
[1 0 0 0 0 0 0 0]
Fear Angry
[1 0 0 0 0 0 0 0]
Disgust Angry
[1 0 0 0 0 0 0 0]
Angry Angry
[1 0 0 0 0 0 0 0]
Fear Angry
[1 0 0 0 0 0 0 0]
Disgust Angry
[1 0 0 0 0 0 0 0]
Neutral Angry
[1 0 0 0 0 0 0 0]
Happy Angry
[1 0 0 0 0 0 0 0]
Fear Angry
[1 0 0 0 0 0 0 0]
Angry Angry
[1 0 0 0 0 0 0 0]
Disgust Angry
[1 0 0 0 0 0 0 0]
Neutral Angry
[1 0 0 0 0 0 0 0]
Sad Angry
[1 0 0 0 0 0 0 0]
Happy Angry
[1 0 0 0 0 0 0 0]
Angry Angry
[1 0 0 0 0 0 0 0]
Angry Angry
[1 0 0 0 0 0 0 0]
Fear Angry
[1 0 0 0 0 0 0 0]
Disgust Angry
[1 0 0 0 0 0 0 0]
Sad Angry
[1 0 0 0 0 0 0 0]
Fear Angry
[1 0 0 0 0 0 0 0]
Sad Angry
[1 0 0 0 0 0 0 0]
Sad Angry
[1 0 0 0 0 0 0 0]
Neutral Angry
[1 0 0 0 0 0 0 0]
Happy Angry
[1 0 0 0 0 0 0 0]
Sad Angry
[1 0 0 0

In [ ]:
history.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy', 'lr'])

In [ ]:
epochs=numpy.arange(100)+1
epochs

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# model=Sequential()
# model.add(layers.Conv1D(256,padding='same',kernel_size=5,activation="relu"))
# model.add(layers.MaxPooling1D(pool_size=5,strides=2,padding="same"))
# model.add(layers.Conv1D(128,padding='same',kernel_size=5,activation="relu"))
# model.add(layers.MaxPooling1D(pool_size=5,strides=2,padding="same"))
# model.add(layers.Conv1D(128,padding='same',kernel_size=5,activation="relu"))
# model.add(layers.MaxPooling1D(pool_size=5,strides=2,padding="same"))
# model.add(layers.Conv1D(64,padding='same',kernel_size=5,activation="relu"))
# model.add(layers.MaxPooling1D(pool_size=5,strides=2,padding="same"))
# model.add(layers.Dropout(rate=0.3))
# model.add(layers.Flatten())
# model.add(layers.Dense(8, activation="softmax"))
# model.compile(Adam(learning_rate=0.0000001),loss="categorical_crossentropy",metrics=["accuracy"])
# rlrp = ReduceLROnPlateau(monitor='loss', factor=0.4, verbose=0, patience=2, min_lr=0.000000001)
# history=model.fit(Train_Set_Data, Train_Set_Label, batch_size=32, epochs=100, validation_data=(Test_Set_Data, Test_Set_Label), callbacks=[rlrp],shuffle=True)
# # model.fit(Train_Set_Data,Train_Set_Label,validation_split=0.2,batch_size=32,epochs=50,verbose=1,shuffle=True,callbacks=[rlrp])
# # print(history)
# # print(history.history.keys())

NameError: ignored

In [ ]:
l1=numpy.array([1,2,3])
l2=numpy.array([4,5,6])
r=numpy.array([])
r=numpy.hstack((r,l1))
r=numpy.hstack((r,l2))
r

array([1.000000, 2.000000, 3.000000, 4.000000, 5.000000, 6.000000])

In [ ]:
l1=numpy.array([1,2,3])
l2=numpy.array([4,5,6])
r=numpy.vstack((l1,l2))
print(r)
numpy.mean(r,axis=0)


[[1 2 3]
 [4 5 6]]


array([2.500000, 3.500000, 4.500000])